In [1]:
#categorical data , data 
#which are descriptive rather than numerically informative

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#importing library for label encoding, OneHotEncoder as we 
#want data in binary format
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#trying stack overflow
from sklearn.compose import ColumnTransformer
#for splitting data set
from sklearn.model_selection import train_test_split
#using linear regression just imput is more tha none
from sklearn.linear_model import LinearRegression
#needed for backward elemeination
import statsmodels.formula.api as sm

In [35]:
data = pd.read_csv(r'/Users/divyashahi/OneDrive - Adobe/Machine_Leaning_Material/Startups_company.csv')

In [36]:
data.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [37]:
#extracting data from data set
real_X = data.iloc[:, 0:4]
real_Y = data.iloc[:, 4]
#real_y

In [38]:
#extracting data from data set
real_X = data.iloc[:, 0:4].values
real_Y = data.iloc[:, 4].values
real_X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [39]:
#extracting data from data set
real_X = data.iloc[:, 0:4].values
real_Y = data.iloc[:, 4].values
#since actual data will be reaquired in 2d array
real_Y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [40]:
#here we have three categorical/ or dummy variable 
#three name of city which we need to encode
#in order to avoid multicolinearity problem

In [61]:
#creating an object of class labelEncoder
le = LabelEncoder()
#going to label encode categorical data, do changes and store in the
#req column
real_X[:, 3] = le.fit_transform(real_X[:, 3])
real_X[:, 3]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [62]:
#but we want data in binary format so need to use one hot encoer
#here we need to pass argument as categorical data
#we have three here thee name of cities
oneHe = OneHotEncoder()
oneHE = OneHotEncoder(categories=[3])

#again transform
real_x = oneHE.fit_transform(real_X).toarray()

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [63]:
#but we want data in binary format so need to use one hot encoer
#here we need to pass argument as categorical data
#we have three here thee name of cities
oneHe = OneHotEncoder()
oneHE = OneHotEncoder( categories='auto')
#again transform
x = real_X
real_X = oneHE.fit_transform(real_X).toarray()
real_X

array([[0., 1., 1., ..., 0., 0., 1.],
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 1., 0.]])

14

You need to use ColumnTransformer to specify the column index not categories parameter.

Constructor parameter categories is to tell distinct category values explicitly. E.g. you could provide [0, 1, 2] explicitly, but auto will determine it. Further, you can use slice() object instead.

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

X = [[0, 'a'], [0, 'b'], [1, 'a'], [2, 'b']]

ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)

X = ct.fit_transform(X)

In [76]:
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [3])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)
X = ct.fit_transform(x)
X

array([[1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [77]:
#splitting training and testing data set
train_X, test_X, train_Y, test_Y = train_test_split(real_X, real_Y, test_size = 0.2, random_state = 0)

In [79]:
#apply regression model
#object variable mlr
MLR = LinearRegression()
#trainngin compleete in next line
MLR.fit(train_X, train_Y)


LinearRegression()

In [71]:
pred_Y = MLR.predict(test_X)

In [72]:
MLR.coef_

array([-7984.63443828,  8788.64621887,  9223.3191479 , -8301.59039468,
       -5937.57313552,  7816.22637167,  8396.79580718, -9092.31235426,
       -5329.66007827,  5241.35413571,  4783.01655464, -3945.14206044,
       -3709.2783466 ,  5502.7380409 ,  5038.41385937, -6105.14919931,
       -4054.75504332,  3750.98136382,  4382.52300044, -3944.98385296,
         491.25817735,  -182.78752504,  1043.37272473, -1220.95742676,
       -3528.06808807,  3851.20859161,  3851.30928438, -3107.48001296,
       -2588.72857904,  2958.51171453,  3344.10154536, -2789.75065541,
          34.69711206,   187.11058905,   132.49299825,  -148.31193102,
       -1000.56351216,  2563.03286474,  1996.37159652, -1682.18504003,
       -2260.91041305,  2551.13852912,  2551.13852912, -2260.91041305,
       -2009.45115885,  2341.62278332,  2341.62278332, -2009.45115885,
       -1284.78004318,  1575.73056566,  1575.73056566, -1284.78004318,
       -1863.56528496,  2118.14181655,  2118.14181655, -1863.56528496,
      

In [73]:
MLR.intercept_

46698.32041414423

In [80]:
#checking
test_Y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [81]:
pred_Y

array([112591.05527263, 107112.20365301, 112591.05527263, 112157.83686637,
       112591.05527263, 120369.75260901, 118779.4681599 , 120369.75260901,
       112591.05527263, 112591.05527263])

In [ ]:
#this is not good way of prediction of multiple linear regression

Backward Elimination

In [ ]:
print("hi")

In [4]:
# to perform backward elimeination we need value of key and an sl may be simple linear regression
# and we get this via it's summary function