In [1]:
#categorical data , data 
#which are descriptive rather than numerically informative

In [82]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#importing library for label encoding, OneHotEncoder as we 
#want data in binary format
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#trying stack overflow
from sklearn.compose import ColumnTransformer
#for splitting data set
from sklearn.model_selection import train_test_split
#using linear regression just imput is more tha none
from sklearn.linear_model import LinearRegression


#for backward elimination the below 2 imports didn't work for me
#needed for backward elemeination
#import statsmodels.formula.api as sm
#import statsmodels.api as sm 
import statsmodels.regression.linear_model as sm
#print (statsmodels.__version__)

In [60]:
data = pd.read_csv(r'/Users/divyashahi/OneDrive - Adobe/Machine_Leaning_Material/Startups_company.csv')

In [61]:
data.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [62]:
#extracting data from data set
real_X = data.iloc[:, 0:4]
real_Y = data.iloc[:, 4]
#real_y

In [63]:
#extracting data from data set
real_X = data.iloc[:, 0:4].values
real_Y = data.iloc[:, 4].values

In [64]:
#here we have three categorical/ or dummy variable 
#three name of city which we need to encode
#in order to avoid multicolinearity problem

In [65]:
#creating an object of class labelEncoder
le = LabelEncoder()
#going to label encode categorical data, do changes and store in the
#req column
real_X[:, 3] = le.fit_transform(real_X[:, 3])
real_X[:, 3]

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0], dtype=object)

In [66]:
#but we want data in binary format so need to use one hot encoer
#here we need to pass argument as categorical data
#we have three here thee name of cities
oneHe = OneHotEncoder()
oneHE = OneHotEncoder( categories='auto')
#again transform
x = real_X
real_X = oneHE.fit_transform(real_X).toarray()
real_X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [67]:
#doing arrangement for dummy variable
#to avoid dummy variable trap we take one less variable(to take one less dummy var)
real_X = real_X[:, 1:]

In [68]:
#splitting training and testing data set
train_X, test_X, train_Y, test_Y = train_test_split(real_X, real_Y, test_size = 0.2, random_state = 0)

In [69]:
#apply regression model
#object variable mlr
MLR = LinearRegression()
#print(train_X)
#print(train_Y)

#trainngin compleete in next line
MLR.fit(train_X, train_Y)


LinearRegression()

In [70]:
pred_Y = MLR.predict(test_X)
#print(pred_Y)

In [71]:
MLR.coef_

array([-16457.05797811, -14088.05088346,  -1220.01323105, -34058.44543027,
       -19356.50306334, -11993.81479938,   7332.6841449 ,   5770.67078243,
       -15335.51712805, -15936.18130071,  -9039.2914175 ,   8800.37872431,
        -6298.66346245, -10309.96858177,  -3121.99657895,  17019.24698517,
        10609.58762243,   3621.83203626,   8113.97766516, -11802.69244912,
         4742.58135891,   3680.00091994,   6144.52122138,   5553.95948143,
        -4798.16542887,  -1450.80400674,  -6588.74377875,   1031.36576745,
        -6490.68217562,  19879.9695412 ,   7270.44121256,  15178.37459168,
        12445.97488861,    165.28663593,  -6387.75362015,    339.3030397 ,
         6832.82672083,   8918.66220527,  19279.76482973,  16432.22567649,
        17469.25730805,  14436.50636822,  18553.07567649,      0.        ,
        23073.46303489,      0.        ,  30442.92567649,  26193.40970156,
        -9657.26084742, -26102.7894268 ,      0.        ,  -5209.11577651,
            0.        ,  

In [72]:
MLR.intercept_

96403.07585714644

In [73]:
#checking
test_Y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [74]:
pred_Y

array([108087.40943475,  94075.52935037, 103684.13111554, 109115.49885826,
       103344.82807584, 119826.12211671,  94325.09783199, 130700.8478805 ,
       108898.78755726, 103344.82807584])

In [75]:
#this is not good way of prediction of multiple linear regression

Backward Elimination

In [76]:
print("hi")


hi


In [77]:
# to perform backward elimeination we need value of key and an sl may be simple linear regression
# and we get this via it's summary function

In [78]:
#y = b0 + b1x1 + b2x2+ .......... + BnXn x0=1 including b0 part with xo as 1
#stats model doesn't take care of our b0 variable
real_X = np.append(arr=np.ones((50,1)).astype(int), values=real_X, axis = 1)

real_X

array([[1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [79]:
#getting all the optimization
#creating optimization model
x_opt = np.array(real_X[:, [0, 1,2,3,4,5]], dtype=float)

In [83]:
#creating an ordinary least square regression model
#import stats
reg_OLS = sm.OLS(endog = real_Y, exog=x_opt).fit()

In [81]:
#print (statsmodels.__version__)

NameError: name 'statsmodels' is not defined

In [84]:
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.203
Model:                            OLS   Adj. R-squared:                  0.113
Method:                 Least Squares   F-statistic:                     2.244
Date:                Thu, 07 Oct 2021   Prob (F-statistic):             0.0665
Time:                        09:30:07   Log-Likelihood:                -594.98
No. Observations:                  50   AIC:                             1202.
Df Residuals:                      44   BIC:                             1213.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.178e+05   5659.867     20.808      0.000    1.06e+05    1.29e+05
x1         -8.209e+04   3.84e+04     -2.139      0.038   -1.59e+05   -4730.369
x2         -5.284e+04   3.84e+04     -1.377      0.176    -1.3e+05    2.45e+04
x3         -6.828e+04   3.84e+04     -1.779      0.082   -1.46e+05    9086.971
x4         -4.801e+04   3.84e+04     -1.251      0.218   -1.25e+05    2.94e+04
x5         -3.654e+04   3.84e+04     -0.952      0.346   -1.14e+05    4.08e+04
==============================================================================
Omnibus:                        1.590   Durbin-Watson:                   0.512
Prob(Omnibus):                  0.452   Jarque-Bera (JB):                0.795
Skew:                          -0.059   Prob(JB):                        0.672
Kurtosis:                       3.606   Cond. No.                         7.47
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [85]:
#following backward elimination
x_opt = real_X[:, [0, 1,2,3,4,5]]
reg_OLS = sm.OLS(endog = real_Y, exog=x_opt).fit()
reg_OLS.summary()
#backward elemination helps us to find var on which our  result best fits the output result
#with minimum error

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.203
Model:                            OLS   Adj. R-squared:                  0.113
Method:                 Least Squares   F-statistic:                     2.244
Date:                Thu, 07 Oct 2021   Prob (F-statistic):             0.0665
Time:                        09:36:13   Log-Likelihood:                -594.98
No. Observations:                  50   AIC:                             1202.
Df Residuals:                      44   BIC:                             1213.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.178e+05   5659.867     20.808      0.000    1.06e+05    1.29e+05
x1         -8.209e+04   3.84e+04     -2.139      0.038   -1.59e+05   -4730.369
x2         -5.284e+04   3.84e+04     -1.377      0.176    -1.3e+05    2.45e+04
x3         -6.828e+04   3.84e+04     -1.779      0.082   -1.46e+05    9086.971
x4         -4.801e+04   3.84e+04     -1.251      0.218   -1.25e+05    2.94e+04
x5         -3.654e+04   3.84e+04     -0.952      0.346   -1.14e+05    4.08e+04
==============================================================================
Omnibus:                        1.590   Durbin-Watson:                   0.512
Prob(Omnibus):                  0.452   Jarque-Bera (JB):                0.795
Skew:                          -0.059   Prob(JB):                        0.672
Kurtosis:                       3.606   Cond. No.                         7.47
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [87]:
#following backward elimination
x_opt = real_X[:, [0, 1,2,3,4]]
reg_OLS = sm.OLS(endog = real_Y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.187
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     2.584
Date:                Thu, 07 Oct 2021   Prob (F-statistic):             0.0496
Time:                        09:37:35   Log-Likelihood:                -595.48
No. Observations:                  50   AIC:                             1201.
Df Residuals:                      45   BIC:                             1211.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.17e+05   5592.160     20.917      0.000    1.06e+05    1.28e+05
x1          -8.13e+04   3.83e+04     -2.121      0.039   -1.59e+05   -4083.603
x2         -5.205e+04   3.83e+04     -1.358      0.181   -1.29e+05    2.52e+04
x3         -6.748e+04   3.83e+04     -1.760      0.085   -1.45e+05    9733.737
x4         -4.721e+04   3.83e+04     -1.232      0.225   -1.24e+05       3e+04
==============================================================================
Omnibus:                        1.208   Durbin-Watson:                   0.460
Prob(Omnibus):                  0.547   Jarque-Bera (JB):                0.481
Skew:                          -0.012   Prob(JB):                        0.786
Kurtosis:                       3.480   Cond. No.                         7.38
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [88]:
#following backward elimination
x_opt = real_X[:, [0, 1,2,3]]
reg_OLS = sm.OLS(endog = real_Y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.159
Model:                            OLS   Adj. R-squared:                  0.105
Method:                 Least Squares   F-statistic:                     2.908
Date:                Thu, 07 Oct 2021   Prob (F-statistic):             0.0445
Time:                        09:37:49   Log-Likelihood:                -596.31
No. Observations:                  50   AIC:                             1201.
Df Residuals:                      46   BIC:                             1208.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.16e+05   5563.332     20.845      0.000    1.05e+05    1.27e+05
x1          -8.03e+04   3.85e+04     -2.083      0.043   -1.58e+05   -2710.722
x2         -5.104e+04   3.85e+04     -1.324      0.192   -1.29e+05    2.65e+04
x3         -6.648e+04   3.85e+04     -1.725      0.091   -1.44e+05    1.11e+04
==============================================================================
Omnibus:                        0.787   Durbin-Watson:                   0.365
Prob(Omnibus):                  0.675   Jarque-Bera (JB):                0.207
Skew:                           0.028   Prob(JB):                        0.902
Kurtosis:                       3.310   Cond. No.                         7.30
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [90]:
#following backward elimination
x_opt = real_X[:, [0, 1,3]]
reg_OLS = sm.OLS(endog = real_Y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.127
Model:                            OLS   Adj. R-squared:                  0.090
Method:                 Least Squares   F-statistic:                     3.430
Date:                Thu, 07 Oct 2021   Prob (F-statistic):             0.0407
Time:                        09:38:23   Log-Likelihood:                -597.25
No. Observations:                  50   AIC:                             1200.
Df Residuals:                      47   BIC:                             1206.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.149e+05   5549.041     20.707      0.000    1.04e+05    1.26e+05
x1         -7.923e+04   3.88e+04     -2.040      0.047   -1.57e+05   -1089.548
x2         -6.541e+04   3.88e+04     -1.684      0.099   -1.44e+05    1.27e+04
==============================================================================
Omnibus:                        0.458   Durbin-Watson:                   0.343
Prob(Omnibus):                  0.796   Jarque-Bera (JB):                0.074
Skew:                           0.061   Prob(JB):                        0.964
Kurtosis:                       3.144   Cond. No.                         7.22
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [91]:
#following backward elimination
x_opt = real_X[:, [0, 1]]
reg_OLS = sm.OLS(endog = real_Y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.075
Model:                            OLS   Adj. R-squared:                  0.055
Method:                 Least Squares   F-statistic:                     3.875
Date:                Thu, 07 Oct 2021   Prob (F-statistic):             0.0548
Time:                        09:38:40   Log-Likelihood:                -598.71
No. Observations:                  50   AIC:                             1201.
Df Residuals:                      48   BIC:                             1205.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.136e+05   5596.183     20.294      0.000    1.02e+05    1.25e+05
x1          -7.79e+04   3.96e+04     -1.969      0.055   -1.57e+05    1665.637
==============================================================================
Omnibus:                        0.172   Durbin-Watson:                   0.216
Prob(Omnibus):                  0.918   Jarque-Bera (JB):                0.033
Skew:                           0.061   Prob(JB):                        0.984
Kurtosis:                       2.966   Cond. No.                         7.15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
#now from here ownward the way is same as linear regression
#we get optimised result if we take 0 th and 1st variable