First notebook for numpy


In [1]:
print("numpy pratice")

numpy pratice


Import numpy if you get error do pip install numpy from terminal

In [2]:
import numpy as np

Basic numpy array

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b = np.array([[2.0,7.4],[1.4, 4.6]])
print(b)

[[2.  7.4]
 [1.4 4.6]]


In [25]:
#declaring dtype explicitly in array
c = np.array([1,4,78,90], dtype='int16')
print(c)

[ 1  4 78 90]


In [14]:
#getting dimension of array
print("dimension of a ")
print(a.ndim)

k = b.ndim
# print("dimension of b"+k) can only concatenate str (not "int") to str
print(k)

dimension of a 
1
2


In [21]:
#getting shape of array 
#print(kc) name 'kc' is not defined
kc = a.shape
print(kc)
print(b.shape)

(3,)
(2, 2)


In [27]:
#get the type of array
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
float64
int16


In [28]:
#getting size of item
print(a.itemsize)
#getting number of elements
print(a.size)
#getting total number of elements
print(a.size*a.itemsize)
#getting total number of items in the list
print(a.nbytes)

8
3
24
24


changing , getting specific rows , columns etx

In [30]:
#printing array
z = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(z)
print(z[1][0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
6


In [32]:
print(z[1,4])

10


In [33]:
#printing via using negative index
print(z[1,-1])

10


In [35]:
#printing column 2
print(z[:,2])

[3 8]


In [38]:
#printing whole column
print(z[0:,])

print(z[0:,])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
#printing one row
print(z[0,:])

[1 2 3 4 5]


In [42]:
#printing first 0 rows, element from 1 to 5 index with step size 2
#print(z[0:, 1:5, 2]) IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
#print(z[0, 1:5, 2]) too many indices for array: array is 2-dimensional, but 3 were indexed
print(z[0, 1:5: 2]) 

[2 4]


In [43]:
#changing a particular element
z[1,4] = 0
print(z)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [45]:
#changing one entire column
z[:,4] = 10
print(z)

[[ 1  2  3  4 10]
 [ 6  7  8  9 10]]


In [47]:
#changin entire column with different values
z[:,4] = [12,13]
print(z)

[[ 1  2  3  4 12]
 [ 6  7  8  9 13]]


In [48]:
#changig entire row
z[0, :] = 11
print(z)

[[11 11 11 11 11]
 [ 6  7  8  9 13]]


In [51]:
#changing some rows with specific elements
z[0, 2:5] = 20
print(z)
z[0, 2:4] = 30
print(z)

[[11 11 20 20 20]
 [ 6  7  8  9 13]]
[[11 11 30 30 20]
 [ 6  7  8  9 13]]


In [52]:
#accessing elements in 3d vector
l = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(l)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
#I want to print 7
print(l[1,1,0])

7


In [54]:
#I want to change second row of first array with 1
l[0,1,:] = 10
print(l)

[[[ 1  2]
  [10 10]]

 [[ 5  6]
  [ 7  8]]]


In [55]:
#I want to change second row of first array with [13,45]
l[0,1,:] = [13,45]
print(l)

[[[ 1  2]
  [13 45]]

 [[ 5  6]
  [ 7  8]]]


In [58]:
#I want to change second row of both internal array with [14,45]
l[:, 1, :] = [[14,45], [10,5]]
print(l)
l[:, 1, :] = [55,55]
print(l)

[[[ 1  2]
  [14 45]]

 [[ 5  6]
  [10  5]]]
[[[ 1  2]
  [55 55]]

 [[ 5  6]
  [55 55]]]


Initialising different types of arrays

In [69]:
#creating arrays filled with zeroes
#a = np.zeroes(2) AttributeError: module 'numpy' has no attribute 'zeroes'
a = np.zeros(2)
print(a)
print("------")
# a = np.zeros(2,2) TypeError: Cannot interpret '2' as a data type
print("------")
a = np.zeros((2,2))
print(a)
print("------")
a = np.zeros((2,2,3))
print(a)
print("------")
a = np.zeros((2,2 ,3,3))
print(a)

[0. 0.]
------
------
[[0. 0.]
 [0. 0.]]
------
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
------
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


In [74]:
#crating arrays with ones
a = np.ones(1)
print(a)
print("----")

#a = np.ones(1,2) TypeError: Cannot interpret '2' as a data type
a = np.ones((1,2))
print(a)
print("----")
a = np.ones((3,3,4), dtype='float32')
print(a)
print("----")

[1.]
----
[[1. 1.]]
----
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
----


In [77]:
#take shape of another number and fill with random number
#a = np.full_like(a) TypeError: _full_like_dispatcher() missing 1 required positional argument: 'fill_value'
a = np.full_like(a, 5)
print(a)

[[[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]

 [[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]

 [[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]]


In [81]:
#generating array with random values
a = np.ones((3,3,4))
# a = np.random.rand(a) TypeError: only integer scalar arrays can be converted to a scalar index
a = np.random.rand(2,3)
print(a)

a = np.random.rand(2,3,3)
print("----")
print(a)

[[0.51458444 0.71761405 0.0353193 ]
 [0.33618819 0.83962468 0.51337514]]
----
[[[0.55189082 0.16880796 0.47933886]
  [0.57431457 0.86152398 0.0456113 ]
  [0.55585628 0.67068578 0.00614029]]

 [[0.05030382 0.12953748 0.02117881]
  [0.20585455 0.28834758 0.63021302]
  [0.61141602 0.49366034 0.94525097]]]


In [92]:
#creating random arrays with integer
# 2 = start, 8 = end excluded , (3, 4) size of the array
a= np.random.randint(2,8, size = (3,4))
print(a)
print("------------")

#8 = end value not included
a= np.random.randint(8, size = (3,4))
print(a)

[[3 3 7 7]
 [5 7 7 4]
 [7 3 3 2]]
------------
[[6 7 5 7]
 [3 0 6 1]
 [5 1 7 7]]


In [93]:
#creating an array similar to given array filled with random value
b= np.random.random_sample(a.shape)
print(b)

[[0.63316048 0.59046325 0.12504749 0.28176872]
 [0.71671528 0.03309643 0.58499646 0.55009893]
 [0.07662555 0.79554851 0.23840431 0.3251253 ]]


In [94]:
#creating identiy matrix
b = np.identity(2)
print(b)
print("------")
b = np.identity(4)
print(b)
print("------")

[[1. 0.]
 [0. 1.]]
------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------


In [100]:
#repeat an arrya
a = np.array([1,2,3])
r = np.repeat(a, 3)
#repeat no need to specify axis in 1d array as it is by default 0
print(r)
print("--------------")
a = np.array([[1,2,3]])
r = np.repeat(a, 4, axis = 0) #repeat along rows
print(r)
print("--------------")

r = np.repeat(a, 4, axis = 1) #repeat along rows
print(r)
print("--------------")


# a = np.array([[1,2,3][2,3,4]])  TypeError: list indices must be integers or slices, not tuple
a = np.array([[1,2,3],[2,3,4],[0,0,0]])
r = np.repeat(a, 4, axis = 0) #repeat along rows
print(r)
print("--------------")



[1 1 1 2 2 2 3 3 3]
--------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
--------------
[[1 1 1 1 2 2 2 2 3 3 3 3]]
--------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
--------------


In [106]:
a = np.ones((5,5))
print(a)
b = np.zeros((3,3))
print(b)
b[1,1] = 9
print(b)
a[1:4,1:4] = b
print("----------")
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
----------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [108]:
#copying one arrray to another ref to same array
a = np.array([1,2,3])
b = a
b[0] = 10
print(a)
print(b)
print("-------")
#to make a copy you need to specify that make a copy
b = a.copy()
b[0] = 20
print(a)
print(b)

[10  2  3]
[10  2  3]
-------
[10  2  3]
[20  2  3]


Mathematics


In [114]:
a = np.array([1,2,3])
a+=2
print(a)
a-=4
print(a)
a*=2
print(a)
a= a ** 2
print(a)
# a/=2 TypeError: No loop matching the specified signature and casting was found for ufunc true_divide
a= a / 2
print(a)
b = np.ones(3)
print(a+b)


[3 4 5]
[-1  0  1]
[-2  0  2]
[4 0 4]
[2. 0. 2.]
[3. 1. 3.]


Trignometry


In [115]:
a = np.sin(a)
print(a)

[0.90929743 0.         0.90929743]


####Linear Algebra different from normal maths follows matrix rule


In [119]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2],[1,2],[1,2]])
#normal multiplication will give error becuase of different row and column values
#so doing matrix multiplication
print(np.matmul(a,b))
#resultant matrix should be 2*2

#getting determinant of identity matrix
c = np.identity(3)
print(np.linalg.det(c)) #should be 1
print(c)

[[ 6 12]
 [15 30]]
1.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Statistics


In [121]:
a = np.array([[1,2,3], [4,5,6]])
k = np.min(a)
print(k)
k = np.min(a, axis = 0)
print(k)

k = np.min(a, axis = 1)
print(k )
print("---------------")
k = np.max(a)
print(k)
k = np.max(a, axis = 0)
print(k)

k = np.max(a, axis = 1)
print(k )
print("---------------")
k = np.sum(a)
print(k)
print("---------------")
k = np.sum(a, axis = 0)
print(k)
print("---------------")
k = np.sum(a, axis = 1)
print(k)

1
[1 2 3]
[1 4]
---------------
6
[4 5 6]
[3 6]
---------------
21
---------------
[5 7 9]
---------------
[ 6 15]


### Rearranging arrays

In [127]:
before = np.random.randint(1, 10, size = (4,2)) #a= np.random.randint(2,8, size = (3,4))
print(before)
after = before.reshape(8,1)
print(a)

[[1 8]
 [1 5]
 [3 6]
 [1 6]]
[[1 2 3]
 [4 5 6]]


In [131]:
#a= np.ones(5) both array much have same size 
a= np.ones(3)
b = np.zeros(3)
print(np.vstack([a,b]))
print(np.vstack([a,b,b]))
print(np.hstack([a,b]))
#stacking of 2d arrays can also be done

[[1. 1. 1.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 0. 0. 0.]


In [132]:
a= np.random.randint(1,100, size = (16,4))
print(a)

[[74 17 86 41]
 [85 48 61 86]
 [32 76  6 28]
 [84 52 42 39]
 [80 32 10 77]
 [ 7 28 75 72]
 [48 11 85 79]
 [67 12 76 13]
 [ 7 99  7 85]
 [60 53 75 17]
 [69  9 79 75]
 [82  8 67 50]
 [46 20 26  3]
 [91 20 82 51]
 [52  4 79 88]
 [20 37 79 41]]


In [133]:
#makes a copy and converts datatype
print(a.astype('float32'))
#original array
print(a)

[[74. 17. 86. 41.]
 [85. 48. 61. 86.]
 [32. 76.  6. 28.]
 [84. 52. 42. 39.]
 [80. 32. 10. 77.]
 [ 7. 28. 75. 72.]
 [48. 11. 85. 79.]
 [67. 12. 76. 13.]
 [ 7. 99.  7. 85.]
 [60. 53. 75. 17.]
 [69.  9. 79. 75.]
 [82.  8. 67. 50.]
 [46. 20. 26.  3.]
 [91. 20. 82. 51.]
 [52.  4. 79. 88.]
 [20. 37. 79. 41.]]
[[74 17 86 41]
 [85 48 61 86]
 [32 76  6 28]
 [84 52 42 39]
 [80 32 10 77]
 [ 7 28 75 72]
 [48 11 85 79]
 [67 12 76 13]
 [ 7 99  7 85]
 [60 53 75 17]
 [69  9 79 75]
 [82  8 67 50]
 [46 20 26  3]
 [91 20 82 51]
 [52  4 79 88]
 [20 37 79 41]]


In [134]:

print(a > 50)

[[ True False  True False]
 [ True False  True  True]
 [False  True False False]
 [ True  True False False]
 [ True False False  True]
 [False False  True  True]
 [False False  True  True]
 [ True False  True False]
 [False  True False  True]
 [ True  True  True False]
 [ True False  True  True]
 [ True False  True False]
 [False False False False]
 [ True False  True  True]
 [ True False  True  True]
 [False False  True False]]


In [135]:
#where ever value is greater than 50 print those
print(a[a>50])

[74 86 85 61 86 76 84 52 80 77 75 72 85 79 67 76 99 85 60 53 75 69 79 75
 82 67 91 82 51 52 79 88 79]


In [138]:
#printing list content as index given in form of list
a = np.array([74, 86, 85 ,77, 75, 72 ])
print(a[[1,2,-1]])

[86 85 72]


In [142]:
a= np.random.randint(1,100, size = (16,4))
print(a)
print("--------")
#if any data along column is greater than 50
print(np.any(a > 50 , axis = 0))
print("--------")
print(((a > 50) & (a < 60)))

[[ 6 22 70 93]
 [15 20 67 76]
 [72 48 31 89]
 [38 64 29  2]
 [ 8 23 91 84]
 [30 21 56 35]
 [68 57 61  2]
 [45 76 81 17]
 [62 16 27 42]
 [80 19 12 10]
 [25 62 90 76]
 [55 24 83 78]
 [37  2 46 20]
 [46 62 33 33]
 [74 95 13 47]
 [35 49 66 16]]
--------
[ True  True  True  True]
--------
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False  True False]
 [False  True False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [ True False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
